---
- set_fact:
    # kinbana container image
    elkf_kibana_image: "{{ elkf_containers | selectattr('name', 'equalto', 'kibana') | map(attribute='image') | first }}"
    # Protocol to be used to connect elasticsearch nodes
    elkf_kibana_to_es_protocol: http

- name: "Pull Kibana image: {{ elkf_stack_version }}"
  docker_image:
    name: "{{ elkf_kibana_image }}"
    tag: "{{ elkf_stack_version }}"
    source: pull

- name: "Start Kibana containers {{ elkf_stack_version }}"
  docker_container:
    name: "{{ kibana_container.node_name }}"
    image: "{{ elkf_kibana_image }}:{{ elkf_stack_version }}"
    ports: 
      - "{{ kibana_container.ports.web }}:5601"
    labels:
      service: kibana
      group:  "{{ elkf_stack_name }}"
    env:
      # names
      "SERVER_NAME": "{{ kibana_container.node_name }}"
      # discovery
      "ELASTICSEARCH_HOSTS": "{{ elastic_search_hosts | to_json(separators=(',',':')) }}"
      # network options
      "SERVER_HOST": "0.0.0.0"
      "SERVER_PORT": "5601"
  loop: "{{ current_host_kibana_containers }}"
  loop_control:
    loop_var: kibana_container
  vars:
    protocol_string_prefix: "{{ elkf_kibana_to_es_protocol }}://"
    elastic_search_hosts: "{{ [protocol_string_prefix]|product(elkf_es_api_endpoints)| map('join') }}"
