---
- name: "Pull filebeat image: {{ elkf_stack_version }}"
  docker_image:
    name: "{{ elkf_stack_image_filebeat }}"
    tag: "{{ elkf_stack_version }}"
    source: pull

- name: "Start filebeat containers"
  docker_container:
    name: "{{ filebeat_container.node_name }}"
    image: "{{ elkf_stack_image_filebeat }}:{{ elkf_stack_version }}"
    labels:
      elkf_stack_cluster_name: "{{ elkf_stack_cluster_name }}"
      elkf_stack_node_name: "{{ filebeat_container.node_name }}"
      elkf_stack_service: filebeat
  loop: "{{ elkf_services_filebeat_ports }}"
  loop_control:
    loop_var: filebeat_container
