elkf_default_version: "7.7.0"
elkf_default_network_name: elastic
elkf_default_stack_name: elkf_default
elkf_group_label: "group={{ elkf_stack.name | default(elkf_default_stack_name) }}"
elkf_containers:
  - name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch
  - name: logstash
    image: docker.elastic.co/logstash/logstash
  - name: kibana
    image: docker.elastic.co/kibana/kibana
  - name: filebeat
    image: docker.elastic.co/beats/filebeat